### ISSUE TITLE
Error in Python when run workflow action

### ISSUE THREAD

**Issue by turgutatashov** [y-mehta/vulnalerts#2]
Hello,
I am running git workflow but receive error in main.py file.Did anyone has the same issue? Please help

Traceback (most recent call last):
  File "/main.py", line 5[8](https://github.com/Turgut202/vulnalerts/runs/6913464149?check_suite_focus=true#step:4:9), in <module>
    main()
  File "/main.py", line 53, in main
    message,cve_count = parse_nvd_feed(get_cpes())
  File "/main.py", line 1[9](https://github.com/Turgut202/vulnalerts/runs/6913464149?check_suite_focus=true#step:4:10), in parse_nvd_feed
    get_nvd_feed()
  File "/main.py", line 9, in get_nvd_feed
    wget.download(url)
  File "/usr/local/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by blentz** [comment]
"In late 2023, the NVD will retire its legacy data feeds while working to guide any remaining data feed users to updated application-programming interfaces (APIs)."

See: https://nvd.nist.gov/vuln/data-feeds
